export const experiences = [
  {
    title: "Senior full stack engineer",
    details: {
      organisation: "HeadBox",
      location: "London",
      dateRange: "June 2022 - Present",
      startDate: "June 2022",
      endDate: "Present",
      roleType: "Permanent",
    },
    technologies: [
      "aws",
      "node",
      "postgresql",
      "git",
      "npm",
      "yarn",
      "eslint",
      "prettier",
      "graphql",
      "apollo",
      "urql",
      "codegen",
      "react",
      "javascript",
      "typescript",
      "html",
      "css",
    ],
    description: [],
  },
  {
    title: "Full stack engineer",
    details: {
      organisation: "HeadBox",
      location: "London",
      startDate: "October 2021",
      endDate: "June 2022",
      roleType: "Permanent",
    },
    technologies: [
      "aws",
      "node",
      "postgresql",
      "git",
      "npm",
      "yarn",
      "eslint",
      "prettier",
      "graphql",
      "apollo",
      "urql",
      "codegen",
      "react",
      "javascript",
      "typescript",
      "html",
      "css",
    ],
    description: [],
  },
  {
    title: "Full stack engineer",
    details: {
      organisation: "WorldRemit",
      location: "London",
      startDate: "March 2020",
      endDate: "October 2021",
      roleType: "Permanent",
    },
    technologies: [
      "node",
      "git",
      "npm",
      "yarn",
      "eslint",
      "prettier",
      "gatsby",
      "react",
      {
        lookUp: "react",
        title: "React Native",
        alt: "React Native logo",
      },
      "javascript",
      "typescript",
      "html",
      "css",
    ],
    description: [
      "Member of a number of teams working on a variety of different projects covering the last 3 years of ",
      "JavaScript technologies including a legacy in house developed SSR and BFF platform, a Next.JS, Gastby.JS,  ",
      "and Material UI monorepo, a React Native Android app and a new REST API built using clean architecture. ",
      "Being a much larger company than any of my previous employers WorldRemit has presented a number of new ",
      "opportunities for me; assisting designers make their designs technically possible, interviewing for ",
      "engineering managers to offer a potential employee perspective, pairing with Android developers to ",
      "overcome problems caused by the interface between React Native and the underlying native Java, and ",
      "working with the security team to manage a last minute upgrade of the bot protection SDK to the new ",
      "partner without affecting the end user experience or Product’s timeline are just a selection.",
    ],
  },
  {
    title: "Founder",
    details: {
      organisation: "Armicus",
      location: "London",
      startDate: "August 2018",
      endDate: "March 2020",
      roleType: "Permanent",
    },
    technologies: [
      "aws",
      "heroku",
      "node",
      "postgresql",
      "graphql",
      "git",
      "npm",
      "apollo",
      "react",
      "javascript",
      "html",
      "css",
    ],
    description: [
      "Unpaid learning sabbatical, the goal was to learn how to architect and build a full-stack software as ",
      "a service product. Written entirely in JavaScript and hosted on AWS and Heroku, the scope of this project ",
      "has afforded a significant amount of personal growth and experience. Initially a blank slate, the project ",
      "started with researching which technologies to use; React and NodeJS were chosen for the front and back ",
      "ends respectively because they share the same language, with GraphQL used for the API, all are free open ",
      "source software and each have extensive ecosystems surrounding them. Over time changes have included ",
      "moving from MongoDB to PostgreSQL to prevent the need for relational logic in the code, replacing AWS ",
      "AppSync (GraphQL API as a service) with Apollo Server to gain greater control over the business logic ",
      "and moving the core logic from AWS Lambdas to Heroku to remove the long wait for first use. Built around ",
      "an advanced template system that allows the user to customise the shape of their data.",
    ],
  },
  {
    title: "Developer",
    details: {
      organisation: "PowerON Platforms",
      location: "London",
      startDate: "September 2016",
      endDate: "August 2018",
      roleType: "Permanent",
    },
    technologies: [
      "azure",
      "sccm",
      "dotNet",
      {
        lookUp: "dotNet",
        title: ".Net WPF",
        alt: ".Net WPF logo",
      },
      "powerShell",
      "cSharp",
    ],
    description: [
      "Working in a small team has afforded a wide number of opportunities, challenges and responsibilities. ",
      "The largest project has been researching, designing and creating a Windows Installer XML bundle containing ",
      "a number of first and third party MSIs from scratch. This included knowledge of the Windows install ",
      "process, WIX syntax to create the bundle and MSI XML markup, C# custom actions to configure the system ",
      "and the Microsoft Monitoring Agent, building a custom bootstrapper including a controller communicating ",
      "with the burn engine and a multi-page GUI using WPF and MVVM, and integrating with a third party WCF API. ",
      "Other projects have included a number of PowerShell scripts running both locally and in Azure using Azure ",
      "Automation and small desktop applications. ",
    ],
  },
  {
    title: "Support Engineer",
    details: {
      organisation: "Cireson",
      location: "London",
      startDate: "August 2015",
      endDate: "September 2016",
      roleType: "Permanent",
    },
    description: [
      "Providing highly technical support to a large customer base, each with unique and complex environments. ",
      "Technologies most frequently utilised include Active Directory, IIS, PowerShell, SQL, SCSM and SCCM. ",
      "While at Cireson I realised the potential for a dedicated application to make the primary product easier ",
      "to use and assist customers in providing log files and other diagnostic information to the Support team. ",
      "Following 6 months of teaching myself C# and WPF in my own time and 3000 lines of code this application ",
      "was well received and the perfect springboard for my next adventure.",
    ],
  },
  {
    title: "Senior Technical analyst",
    details: {
      organisation: "Rocksteady Studios Ltd",
      location: "London",
      startDate: "May 2013",
      endDate: "August 2015",
      roleType: "Permanent",
    },
    description: [
      "Responsible for managing and providing all first line and second line activities in a highly technically ",
      "complex environment for a user base of between 130 and 170 (headcount increased as the project progressed). ",
      "Responsibilities included all department PowerShell scripting, management of SCCM, deployment of SCSM, ",
      "imaging for desktop deployments using WDS, providing assistance to infrastructure engineer with networking ",
      "and server estate, hardware procurement and stock management.",
    ],
  },
];

export const projects = [
  {
    title: "alextuppen.com",
    technologies: [
      "aws",
      "git",
      "yarn",
      "eslint",
      "prettier",
      "nextjs",
      "react",
      "typescript",
      "html",
      "css",
    ],
    description: [],
  },
];

export const education = [
  {
    title: "BA Hons Business Management",
    details: {
      organisation: "The University of Derby",
      location: "Derby",
      startDate: "2009",
      endDate: "2013",
      roleType: "Full time student",
    },
  },
  {
    title: "Economics, Business Studies, Physics, Chemistry and Maths",
    details: {
      organisation: "Colchester Sixth College",
      location: "Colchester",
      startDate: "2006",
      endDate: "2008",
      roleType: "Full time student",
    },
  },
];
